### ISSUE TITLE
Cartographie 

### ISSUE THREAD

**Issue by YaBoiiiiiiiiii** [RimorRes/MDRS_Rover#4]
Je voudrais bien le faire. Mais si cela ne vous gêne pas, ou si vous ne pensiez pas que demander ce genre de question vous ennuis  , je souhaite poser quelques questions  qui nous aiderons pour avoir une possible meilleur idée de ce qu'on pourrait coder , les voici  ; 
- Est ce que la cartographie marche à peu près cette manière ?  (dans ce cas):
   On enregistre la hauteur de ce qui se trouve juste devant le capteur (ou sa profondeur)(grâce au capteur) et on affiche sa profondeur/hauteur avec des couleurs sur la carte. 
   Comment faire si on devrait cartographier une zone qui se trouve hors de la porté du rover, par exemple si il y avait soudain un énorme trous 20 mètres plus profond que là où se trouve le rover. Comment allons nous marquer sur la carte ce genre d'endroit où le capteur n'est probablement pas assez bon pour y voir ?
Dernière questions (désolé ça devient long), devons nous afficher différemment les bâtiments au terrain (par exemple) ?

**Comment by Nihoncraft** [comment]
Je pense avoir accidentellement effacer les fichier de cartographie lors de mon dernier commit. Pourrais tu les recommit car je ne les ait pas retrouvé. Je pense qu'ils sont encore dans tes fichiers. Il est possible qu'ils seront commit si tu commit à nouveau. Merci.
